server:
  shutdown: graceful
spring:
  main:
    allow-bean-definition-overriding: true
  devtools:
    restart:
      enabled: false
  rsocket:
    server:
      transport: websocket
      port: 9090
  data:
    mongodb:
      auto-index-creation: true
      uuid-representation: standard
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

spring.main.web-application-type: none

management:
  endpoints:
    web:
      exposure:
        include: metrics, prometheus, health

---
spring:
  config:
    import: classpath:aws-properties.yml
    activate:
      on-profile: local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
logging:
  level:
    root: ${chat.api.logging.level.root:DEBUG}
    org.springframework.data.convert.CustomConversions: ERROR
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: ${chat.api.logging.level.mongo:INFO}
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
    io:
      spring:
        cloud: INFO
  config: classpath:logback-spring-${spring.profiles.active}.xml
---
spring:
  config:
    import: classpath:aws-properties-dev.yml
    activate:
      on-profile: dev
logging:
  level:
    root: ${chat.api.logging.level.root:INFO}
    org.springframework.data.convert.CustomConversions: ERROR
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: ${chat.api.logging.level.mongo:INFO}
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
    io:
      spring:
        cloud: INFO
  config: classpath:logback-spring-${spring.profiles.active}.xml
---
spring:
  config:
    import: classpath:aws-properties-eks-dev.yml
    activate:
      on-profile: eks-dev
logging:
  level:
    root: ${chat.api.logging.level.root:INFO}
    org.springframework.data.convert.CustomConversions: ERROR
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: ${chat.api.logging.level.mongo:INFO}
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
    io:
      spring:
        cloud: INFO
  config: classpath:logback-spring-${spring.profiles.active}.xml
---
spring:
  config:
    import: classpath:aws-properties-qa.yml
    activate:
      on-profile: qa
logging:
  level:
    root: ${chat.api.logging.level.root:INFO}
    org.springframework.data.convert.CustomConversions: ERROR
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: ${chat.api.logging.level.mongo:INFO}
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
    io:
      spring:
        cloud: INFO
  config: classpath:logback-spring-${spring.profiles.active}.xml
---
spring:
  config:
    import: classpath:aws-properties-prod.yml
    activate:
      on-profile: prod
logging:
  level:
    root: ${chat.api.logging.level.root:INFO}
    org.springframework.data.convert.CustomConversions: ERROR
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: ${chat.api.logging.level.mongo:INFO}
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
    io:
      spring:
        cloud: INFO
  config: classpath:logback-spring-${spring.profiles.active}.xml